### ISSUE TITLE
Constant FM_TYPE_UNKNOWN already defined in FieldMap.php at line 5

### ISSUE THREAD

**Issue by MarinoRaul** [jasonhinkle/phreeze#169]
Hello!

I am configured the framework in windows XAMP environment and I got this error:

Constant FM_TYPE_UNKNOWN already defined in FieldMap.php at line 5

Stack Trace:
#0 [internal function]: ExceptionThrower::HandleError(8, 'Constant FM_TYP...', 'C:\xampp\htdocs...', 5, Array)
#1 C:\xampp\htdocs\phreeze\libs\verysimple\Phreeze\FieldMap.php(5): define('FM_TYPE_UNKNOWN', 0)
#2 C:\xampp\htdocs\phreeze\libs\verysimple\Phreeze\IDaoMap2.php(5): require_once('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\backend\libs\Model\DAO\CompraMap.php(6): require_once('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\backend\libs\Model\DAO\CompraDAO.php(6): require_once('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\backend\libs\Model\Compra.php(5): require_once('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\backend\libs\Controller\CompraController.php(6): require_once('C:\xampp\htdocs...')
#7 phar://C:/xampp/htdocs/backend/libs/phreeze-3.3.phar/verysimple/Phreeze/Dispatcher.php(79): include_once('C:\xampp\htdocs...')
#8 C:\xampp\htdocs\backend\index.php(28): Dispatcher::Dispatch(Object(Phreezer), Object(SavantRenderEngine), '', NULL, Object(GenericRouter))
#9 {main}

Someome can help me????

Thanks!

**Comment by rahulsh1** [comment]
Env: Windows 7.1 , php 5.4.3
I had the same problem. I had both the phar as well as the phreeze folder. When I removed the phreeze folder, I started getting:
`Fatal error: main(): Failed opening required 'verysimple/Phreeze/IDaoMap2.php' `
I ended up removing the phar file and kept the phreeze folder on the server. It works then !!
Is there a way to get the phar to work?
Btw, thanks for creating such a awesome tool.

**Comment by jasonhinkle** [comment]
Ah, I suspect the reason is because the pre-packaged .phar file is outdated and doesn't include the IDaoMap2.php file.  I'll re-package a new phar file so that problem should go away.

You can also build a .phar file from source - just have a look the phreeze/phar folder, there is a php script that will build it for you from the latest source.
