### ISSUE TITLE
Phreeze Builder error

### ISSUE THREAD

**Issue by msiron** [jasonhinkle/phreeze#244]
When I hit 'Analyze Database' I get this error:

Undefined index: Material Types_singular in GeneratorController.php at line 181

With the following stack trace:
#0 /var/www/html/phreeze/builder/libs/Controller/GeneratorController.php(181): ExceptionThrower::HandleError(8, 'Undefined index...', '/var/www/html/p...', 181, Array)
#1 [internal function]: GeneratorController->Generate()
#2 /var/www/html/phreeze/libs/verysimple/Phreeze/Dispatcher.php(161): call_user_func(Array)
#3 /var/www/html/phreeze/builder/index.php(23): Dispatcher::Dispatch(Object(Phreezer), Object(SavantRenderEngine), '', NULL, Object(GenericRouter))
#4 {main}

Note: Material Types is a table in my database

**Comment by stevetx30** [comment]
Right now Phreeze does not support spaces in table names:  Right now you have to use
`Material_Types` or something like `MaterialTypes`
